version: '3.7'

services:
  frontend-dev:
    build:
      context: ./
      target: dev
    command: sh -c 'yarn install && yarn run dev'
    volumes:
      - .:/usr/src/app
      - node_modules
    ports:
      - '3000:3000'

